### ISSUE TITLE
$>ls | cat | wc $>echo seven $>ls

### ISSUE THREAD

**Issue by Gotr-byte** [LukasKava/Minishell#56]
BiebianOS> ls | cat | wc
      9       9      81
BiebianOS> echo seven
seven
BiebianOS> ls
includes  libft  makefile  minishell  minishell.dSYM  README.md  src  tester  tester.tar
BiebianOS> cd libft
BiebianOS> ls
ft_atoi.c     ft_isalpha.o  ft_memchr.c   ft_memset.o      ft_split.c     ft_strjoin.o  ft_strncmp.c  ft_substr.o
ft_atoi.o     ft_isascii.c  ft_memchr.o   ft_putchar_fd.c  ft_split.o     ft_strlcat.c  ft_strncmp.o  ft_tolower.c
ft_bzero.c    ft_isascii.o  ft_memcmp.c   ft_putchar_fd.o  ft_strchr.c    ft_strlcat.o  ft_strnstr.c  ft_tolower.o
ft_bzero.o    ft_isdigit.c  ft_memcmp.o   ft_putendl_fd.c  ft_strchr.o    ft_strlcpy.c  ft_strnstr.o  ft_toupper.c
ft_calloc.c   ft_isdigit.o  ft_memcpy.c   ft_putendl_fd.o  ft_strdup.c    ft_strlcpy.o  ft_strrchr.c  ft_toupper.o
ft_calloc.o   ft_isprint.c  ft_memcpy.o   ft_putnbr_fd.c   ft_strdup.o    ft_strlen.c   ft_strrchr.o  libft.a
ft_isalnum.c  ft_isprint.o  ft_memmove.c  ft_putnbr_fd.o   ft_striteri.c  ft_strlen.o   ft_strtrim.c  libft.h
ft_isalnum.o  ft_itoa.c     ft_memmove.o  ft_putstr_fd.c   ft_striteri.o  ft_strmapi.c  ft_strtrim.o  Makefile
ft_isalpha.c  ft_itoa.o     ft_memset.c   ft_putstr_fd.o   ft_strjoin.c   ft_strmapi.o  ft_substr.c
BiebianOS> 
Ctrl-D was activated a

=================================================================
==20383==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x7f790b317867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55c82f9fc544 in ft_calloc (/home/piotr/code/mini_v3/minishell+0x1b544)
    #2 0x55c82f9f0f17 in ft_strtrim_beginning src/parsing/expansions_utils.c:29
    #3 0x55c82f9f3d59 in reset_old_pwd src/builtins/cd.c:25
    #4 0x55c82f9f4f65 in builtins_cd src/builtins/cd.c:177
    #5 0x55c82f9fb7bd in cd_handle src/execute/builtin_handles.c:38
    #6 0x55c82f9f897a in no_fork_handle src/execute/new_fork.c:80
    #7 0x55c82f9f8d2e in built_in_handler src/execute/new_fork.c:108
    #8 0x55c82f9f921d in execute src/execute/new_fork.c:145
    #9 0x55c82f9e5dcb in parsing_and_execution src/parsing/main.c:126
    #10 0x55c82f9e607a in main src/parsing/main.c:158
    #11 0x7f790b010d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

**Comment by Gotr-byte** [comment]
Most likely cd error.
